# Generated by Django 5.1.7 on 2025-05-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_lessonsteps'),
        ('users', '0007_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userauth'),
        ),
    ]
