# Generated by Django 5.1.7 on 2025-05-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_alter_userlessonprogress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learn.category'),
            preserve_default=False,
        ),
    ]
