# Generated by Django 5.1.7 on 2025-03-30 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('login_type', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('microsoft', 'Microsoft')], default='email', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('profile_picture', models.URLField(blank=True, max_length=1000, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('native_language', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=100)),
                ('daily_goal', models.IntegerField(default=10)),
                ('requirement', models.CharField(choices=[('Other', 'Other'), ('Just for Fun', 'Low'), ('Friends', 'Mid'), ('Family', 'High'), ('Work', 'Vhigh')], default='Other', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.userauth')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
