# Generated by Django 5.1.7 on 2025-03-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userauth_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
