# Generated by Django 5.1.7 on 2025-04-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userauth_password_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='password_hash',
            new_name='password',
        ),
    ]
